//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUS_DEL_DIA
    {
        public int Menu_ID { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
    }
}
