//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafeteria_ESIME_CulhuacanEntities : DbContext
    {
        public cafeteria_ESIME_CulhuacanEntities()
            : base("name=cafeteria_ESIME_CulhuacanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<SUBCATEGORIAS> SUBCATEGORIAS { get; set; }
        public virtual DbSet<MENUS_DEL_DIA> MENUS_DEL_DIA { get; set; }
        public virtual DbSet<vw_Productos> vw_Productos { get; set; }
    }
}
