//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public int ProductoID { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public int Categoria_ID { get; set; }
        public Nullable<int> Subcategoria_ID { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        public virtual CATEGORIAS CATEGORIAS1 { get; set; }
        public virtual SUBCATEGORIAS SUBCATEGORIAS { get; set; }
        public virtual SUBCATEGORIAS SUBCATEGORIAS1 { get; set; }
    }
}
